CREATE DATABASE TCC

USE TCC
GO 

CREATE TABLE CADASTRO_USUARIO
(
	 cpf_usuario VARCHAR(50) NOT NULL PRIMARY KEY,
	 nome_usuario VARCHAR(50) NOT NULL,
	 email_usuario VARCHAR(50) NOT NULL,
	 senha_usuario VARCHAR(50) NOT NULL	
)

CREATE TABLE FASE_1
(
	id_f1 INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	cpf_usuario VARCHAR(50) NOT NULL,
	data_f1 VARCHAR(50) NOT NULL,
	pontuacao_f1 VARCHAR(50) NOT NULL,

	CONSTRAINT FK_CADASTRO_FASE1 FOREIGN KEY(cpf_usuario)
	REFERENCES CADASTRO_USUARIO(cpf_usuario)
)

CREATE TABLE FASE_2
(
	id_f2 INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	cpf_usuario  VARCHAR(50) NOT NULL,
	data_f2  VARCHAR(50) NOT NULL,
	pontuacao_f2 VARCHAR(50) NOT NULL,
	
	CONSTRAINT FK_CADASTRO_FASE2 FOREIGN KEY(cpf_usuario)
	REFERENCES CADASTRO_USUARIO(cpf_usuario)
)

select * from FASE_2

